In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
import pandas as pd
import seaborn as sn

#load and print dataset
data = pd.read_csv(r"C:\Users\hp\Desktop\AIDS\AIDS\car_data.csv")
print("CAR DATASET")
data

CAR DATASET

     User ID  Gender  Age  AnnualSalary  Purchased
0        385    Male   35         20000          0
1        681    Male   40         43500          0
2        353    Male   49         74000          0
3        895    Male   40        107500          1
4        661    Male   25         79000          0
..       ...     ...  ...           ...        ...
995      863    Male   38         59000          0
996      800  Female   47         23500          0
997      407  Female   28        138500          1
998      299  Female   48        134000          1
999      687  Female   44         73500          0

[1000 rows x 5 columns]

In [8]:
#remove rows with missing values
data.dropna(axis=0, inplace=True)

#encode Gender column from categorical to numeric 
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])

#separate target variable(y) and feature set(x)
y = data['Purchased']
x = data.drop(['Purchased'],axis=1)

#split data into training and testing sets 
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=29)

#standardize feature values
scaler = StandardScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)

#create and train a logistic regression model
model = LogisticRegression()
p = model.fit(xtrain_scaled,ytrain)

#predict labels for the test set
xt = p.predict(xtest_scaled)

print("ACCURACY: ",accuracy_score(ytest,xt)*100,"%")

#create a new sample for prediction
new_data = pd.DataFrame({
    "User ID" : [661],
    "Gender" : [1],
    "Age" : [25],
    "AnnualSalary" : [79000]
})
#scaling transformation for new data
new_data_scaled = scaler.transform(new_data)

#predict purchase decision for new data
xt = p.predict(new_data_scaled)

print("\nPREDICTION v/s ACTUAL VALUE: ")
print("----------------------------\n")
print("Y Prediction: ",xt)
print("Actual Y: ",y.iloc[4])

#extract feature names
feature_names = x.columns if hasattr(x, 'columns') else [f'Feature {i}' for i in range(x.shape[1])]

#get model coefficients for each feature
coefficients = model.coef_[0]

#dataframe
feature_importance = pd.DataFrame({
    'Feature' : feature_names,
    'Coefficient' : coefficients
})

#sort features by their coefficient values
feature_importance = feature_importance.sort_values(by = 'Coefficient', ascending=True)

print("FEATURE IMPORTANCE:")
print("-------------------")
feature_importance

ACCURACY:  79.5 %

PREDICTION v/s ACTUAL VALUE:
----------------------------

Y Prediction:  [0]
Actual Y:  0
FEATURE IMPORTANCE:
-------------------

        Feature  Coefficient
0       User ID     0.011877
1        Gender     0.161610
3  AnnualSalary     1.110411
2           Age     2.338559

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = pd.read_csv(r"C:\Users\hp\Desktop\AIDS\AIDS\happydata.csv")
print("Happy Dataset:\n")
data

Happy Dataset:

,infoavail,housecost,schoolquality,policetrust,streetquality,ëvents,happy
0,3,3,3,4,2,4,0
1,3,2,3,5,4,3,0
2,5,3,3,3,3,5,1
3,5,4,3,3,3,5,0
4,5,4,3,3,3,5,0
...,...,...,...,...,...,...,...
138,5,3,3,1,3,5,0
139,5,2,3,4,2,5,1
140,5,3,3,4,4,5,1
141,4,3,3,4,4,5,0
142,5,3,2,5,5,5,0

In [14]:
#remove missing values
data.dropna(axis=0, inplace=True)

#create label encoder
le = LabelEncoder()

#separate target variable(y) and feature set(x)
y = data['happy']
x = data.drop(['happy'],axis=1)

#split the dataset into training and testing sets
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=100)

#standardize features
scaler = StandardScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)


#create and train logistic regression model
model = LogisticRegression()
p = model.fit(xtrain_scaled,ytrain)

#predict labels for the test set
xt = p.predict(xtest_scaled)

print("ACCURACY: ",accuracy_score(ytest,xt)*100,"%")

#create a new sample for prediction
new_data = pd.DataFrame({
    "infoavail" : [3],
    "housecost" : [2],
    "schoolquality" : [2],
    "policetrust" : [5],
    "streetquality" : [4],
    "ëvents" : [3],
})
#scale the new sample 
new_data_scaled = scaler.transform(new_data)

#predict happiness value for the new sample
xt = p.predict(new_data_scaled)

print("\nPREDICTION v/s ACTUAL VALUE: ")
print("----------------------------\n")
print("Y Prediction: ",xt)
print("Actual Y: ",y.iloc[4])

#get feature names
feature_names = x.columns if hasattr(x, 'columns') else [f'Feature {i}' for i in range(x.shape[1])]

#get model coefficients for each feature
coefficients = model.coef_[0]

#dataframe
feature_importance = pd.DataFrame({
    'Feature' : feature_names,
    'Coefficient' : coefficients
})


#sort features by their coefficient values
feature_importance = feature_importance.sort_values(by = 'Coefficient', ascending=True)

print("\nFEATURE IMPORTANCE:")
print("-------------------")
feature_importance

ACCURACY:  62.06896551724138 %

PREDICTION v/s ACTUAL VALUE:
----------------------------

Y Prediction:  [0]
Actual Y:  0

FEATURE IMPORTANCE:
-------------------

         Feature  Coefficient
1      housecost    -0.026113
4  streetquality    -0.001228
2  schoolquality     0.128628
3    policetrust     0.174426
5         ëvents     0.361645
0      infoavail     0.556717