In [22]:
import seaborn as sn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder

iris = sn.load_dataset("iris")
print("\nIris Dataset:\n")
iris

Iris Dataset:

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
print("\nGroup species by size:\n")
iris.groupby('species').size()

Group species by size:

species
setosa        50
versicolor    50
virginica     50
dtype: int64

In [7]:
print("\nGroup species by mean:\n")
iris.groupby('species').mean()

Group species by mean:

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [17]:
print("\nGroup species by sum:\n")
iris.groupby('species').sum()

Group species by sum:

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             250.3        171.4          73.1         12.3
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [23]:
#encode categorical columns
le = LabelEncoder()
iris["species"] = le.fit_transform(iris["species"])

#define target and features
y = iris["petal_width"]
x = iris.drop("petal_width", axis=1)

#split data
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3, random_state=44)

#train model
model = LinearRegression()
p = model.fit(xtrain,ytrain)

#predict and evaluate
xt = p.predict(xtest)
print(f"R2 SCORE(in percentage): {r2_score(ytest, xt)*100:.2f}%")

#predict on new data
new_data = pd.DataFrame({
    "sepal_length" : [5.1],
    "sepal_width" : [3.5],
    "petal_length" : [1.4],
    "species" : [0]
})
xt = p.predict(new_data)

print("\nPREDICTION v/s ACTUAL VALUE: ")
print("Y Prediction: ",xt)
print("Actual Y: ",y[0])

R2 SCORE(in percentage): 94.53%

PREDICTION v/s ACTUAL VALUE:
Y Prediction:  [0.24002959]
Actual Y:  0.2

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import seaborn as sn

#load and print dataset
data = pd.read_csv(r"C:\Users\hp\Desktop\AIDS\AIDS\Salary Data.csv")
data.dropna(axis=0, inplace=True)
print("SALARY DATASET")
data

SALARY DATASET

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [54]:
print("\nGroup job title by size:\n")
data.groupby('Job Title').size()

Group job title by size:

Job Title
Account Manager                 1
Accountant                      1
Administrative Assistant        2
Business Analyst                2
Business Development Manager    1
                               ..
UX Designer                     1
UX Researcher                   1
VP of Finance                   1
VP of Operations                1
Web Developer                   1
Length: 174, dtype: int64

In [53]:
print("\nGroup job title by sum:\n")
data.groupby('Job Title').sum()

Group job title by sum:

,Age,Gender,Education Level,Years of Experience,Salary
Job Title,,,,,
Account Manager,32.0,Male,Bachelor's,5.0,75000.0
Accountant,31.0,Female,Bachelor's,4.0,55000.0
Administrative Assistant,75.0,FemaleFemale,Bachelor'sBachelor's,18.0,100000.0
Business Analyst,67.0,FemaleMale,Master'sBachelor's,12.0,155000.0
Business Development Manager,34.0,Male,Master's,8.0,90000.0
...,...,...,...,...,...
UX Designer,34.0,Female,Master's,5.0,80000.0
UX Researcher,27.0,Female,Master's,2.0,65000.0
VP of Finance,47.0,Male,Master's,19.0,200000.0
VP of Operations,47.0,Male,Master's,19.0,190000.0
Web Developer,33.0,Male,Bachelor's,6.0,65000.0

In [27]:
#encode categorical columns
le = LabelEncoder()
data["Job Title"] = le.fit_transform(data["Job Title"])
data["Education Level"] = le.fit_transform(data["Education Level"])
data["Gender"] = le.fit_transform(data["Gender"])  # Fix for the error

#define target and features
y = data["Salary"]
x = data.drop("Salary", axis=1)

#split data
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.4, random_state=100)

#train model
model = LinearRegression()
ml = model.fit(xtrain, ytrain)

#predict and evaluate
ypred = ml.predict(xtest)
print(f"R2 SCORE (in percentage): {r2_score(ytest, ypred)*100:.2f}%")

#predict on new data
new_data = pd.DataFrame({
    "Age": [32.0],
    "Gender": [1],  
    "Education Level": [2], 
    "Job Title": [0],        
    "Years of Experience": [5.0]
})
new_pred = ml.predict(new_data)

#print prediction vs actual
print("\nPREDICTION v/s ACTUAL VALUE:")
print("Y Prediction:", new_pred)
print("Actual Y:", y.iloc[0])

R2 SCORE (in percentage): 91.59%

PREDICTION v/s ACTUAL VALUE:
Y Prediction: [93298.03451747]
Actual Y: 90000.0